version: "3.8"
services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:5432
    restart: always

  site:
    build: .
    restart: always
    ports:
      - 127.0.0.1:${APP_LOCAL_PORT-3000}:3000
    depends_on:
      - db
