version: "3.8"
services:
  db:
    container_name: ${DB_CONTAINER_NAME:-site-db-develop}
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:5432
    restart: always

  site:
    container_name: ${FRONT_CONTAINER_NAME:-site-front-develop}
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:${APP_LOCAL_PORT-3000}:3000
    depends_on:
      - db

volumes:
  db_data:
