version: "3.8"
services:
  site:
    build: .
    restart: always
    ports:
      - 127.0.0.1:${APP_LOCAL_PORT-3000}:3000

  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      # PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_SERVER}:${LOCAL_DB_PORT}:5432
    restart: always
