services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-qwerty}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${DATABASE_PASSWORD:-qwerty}
      PGUSER: ${DATABASE_USERNAME:-postgres}
    ports:
      - 127.0.0.1:${DATABASE_LOCAL_PORT:-5432}:5432

  back:
    image: simple2b/site-s2b-back
    build:
      context: back_v2
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URI: postgresql://${DATABASE_USERNAME:-postgres}:${DATABASE_PASSWORD:-qwerty}@db/db
    depends_on:
      - db
    ports:
      - 127.0.0.1:${FORWARD_BACK_PORT:-5000}:80

  web:
    image: simple2b/site-s2b-front
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:${APP_LOCAL_PORT:-3000}:3000
    env_file:
      - .env

volumes:
  db_data:
