# docker-compose for deployment
version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${DATABASE_PASSWORD}
      PGUSER: ${DATABASE_USERNAME}

  site:
    image: simple2b/site-s2b-front:1.4.26
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:${APP_LOCAL_PORT}:3000
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.site_dev.rule=Host(`dev.simple2b.net`, `dev.simple2b.org`, `dev.simple2b.de`)'
      - 'traefik.http.routers.site_dev.tls=true'
      - 'traefik.http.routers.site_dev.tls.certresolver=myresolver'

  back:
    image: simple2b/site-s2b-back:1.4.26
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URI: ${DATABASE_URI}
    depends_on:
      - db

  admin:
    image: simple2b/site-s2b-admin:1.0
    command: sh ./start_server.sh
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URI: ${DATABASE_URI}
      APP_ENV: production
    depends_on:
      - back
    ports:
      - 127.0.0.1:${FORWARD_ADMIN_PORT}:80
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.admin_site_dev.rule=Host(`dev.admin.site.simple2b.net`)'
      - 'traefik.http.routers.admin_site_dev.tls=true'
      - 'traefik.http.routers.admin_site_dev.tls.certresolver=myresolver'
  backup:
    image: simple2b/pg-backup:1.0
    restart: unless-stopped
    links:
      - db
    volumes:
      - ./backup:/backup
    environment:
      # scheduler for every 3 days
      APP_ENV: production
      SCHEDULE_DAY: ${SCHEDULE_DAY:-3}
      POSTGRES_DATABASE: db
      POSTGRES_HOST: db
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_EXTRA_OPTS: '--schema=public --blobs'
      DAYS_HISTORY: 7
      SCHEDULE_HOUR: 0
      SCHEDULE_MINUTE: 0
      SCHEDULE_SECOND: 0
      S3_REGION: ${S3_REGION:-**None**}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-**None**}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-**None**}
      S3_BUCKET: ${S3_BUCKET:-**None**}
      S3_PREFIX: ${S3_PREFIX:-**None**}
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-**None**}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-**None**}
      AWS_DEFAULT_REGION: ${S3_REGION:-**None**}

networks:
  default:
    name: site_network

volumes:
  db_data:
