services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${DATABASE_PASSWORD}
      PGUSER: ${DATABASE_USERNAME}
    ports:
      - 127.0.0.1:${DATABASE_LOCAL_PORT}:5432

  back:
    image: simple2b/site-s2b-back
    build:
      context: back_v2
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URI: ${PROD_DATABASE_URI}
    depends_on:
      - db
    # ports:
    #   - 127.0.0.1:${FORWARD_BACK_PORT}:80

  web:
    image: simple2b/site-s2b-front
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:${APP_LOCAL_PORT}:3000
    env_file:
      - .env

volumes:
  db_data:
