services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-secret}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${DATABASE_PASSWORD:-secret}
      PGUSER: ${DATABASE_USERNAME:-postgres}
    ports:
      - 127.0.0.1:${DATABASE_LOCAL_PORT:-5432}:5432

  back:
    build:
      context: back
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ${DOTENV_FILE:-project.env}
    environment:
      DATABASE_URI: postgresql://${DATABASE_USERNAME:-postgres}:${DATABASE_PASSWORD:-qwerty}@db/db
    depends_on:
      - db
    ports:
      - 127.0.0.1:${FORWARD_BACK_PORT:-5000}:80

  admin:
    image: simple2b/site-s2b-admin
    restart: always
    command: sh ./start_server.sh
    env_file:
      - ${DOTENV_FILE:-project.env}
    environment:
      DEVEL_DATABASE_URL: postgresql://${DATABASE_USERNAME:-postgres}:${DATABASE_PASSWORD:-qwerty}@db/db
    depends_on:
      - back
    ports:
      - 127.0.0.1:${FORWARD_ADMIN_PORT:-5001}:8000

  web:
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:${APP_LOCAL_PORT:-3000}:3000
    env_file:
      - ${DOTENV_FILE:-project.env}

volumes:
  db_data:
