services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${DATABASE_PASSWORD}
      PGUSER: ${DATABASE_USERNAME}
    ports:
      - 127.0.0.1:${DATABASE_LOCAL_PORT:-15432}:5432

  back:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      # APP_ENV: production # TODO remove in future
      DATABASE_URI: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db/db
    depends_on:
      - db
    ports:
      - 127.0.0.1:${FORWARD_BACK_PORT:-8000}:80


  web:
    image: simple2b/site-s2b-front
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:${APP_LOCAL_PORT}:3000
    env_file:
      - .env

volumes:
  db_data: