version: "3.8"
services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: db
      POSTGRES_USER: ${DATABASE_USERNAME}
      PGUSER: ${DATABASE_USERNAME}
      PGDATABASE: db
      PGPASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 127.0.0.1:${DATABASE_LOCAL_PORT}:5432
    restart: always

  back:
    build: backend
    restart: always
    command: bash ./start_server.sh
    env_file:
      - .env
    environment:
      DATABASE_URI: ${DATABASE_URI}
    ports:
      - 127.0.0.1:${FORWARD_BACK_PORT}:80
    depends_on:
      - db

    # site:
    # TODO not implemented
    #   build: frontend
    #   restart: always
    #   env_file:
    #     - .env
    #   ports:
    #     - 127.0.0.1:${APP_LOCAL_PORT-3000}:3000
    #   depends_on:
    #     - db

volumes:
  db_data: