version: "3.8"
services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: db
      POSTGRES_USER: ${DATABASE_USERNAME}
      PGUSER: ${DATABASE_USERNAME}
      PGDATABASE: db
      PGPASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 127.0.0.1:${DATABASE_LOCAL_PORT}:5432
    restart: always

  back:
    build: backend
    restart: always
    command: bash ./start_server.sh
    env_file:
      - .env
    environment:
      DATABASE_URI: ${DATABASE_URI}
    ports:
      - 127.0.0.1:${FORWARD_BACK_PORT}:80
    depends_on:
      - db

  nextjs_app:
    build: frontend
    command: node server.js
    env_file:
      - .env
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

volumes:
  db_data:
