version: "3"
services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: db
      POSTGRES_USER: postgres
    ports:
      - 127.0.0.1:${DATABASE_LOCAL_PORT}:5432
    restart: always

  app:
    # image: istacat/storysurvey
    build: .
    restart: always
    command: bash ./start_server.sh
    environment:
      DATABASE_URI: ${PROD_DATABASE_URI}
    ports:
      - 127.0.0.1:8008:80
    depends_on:
      - db

volumes:
  db_data:
