def md_quote(text):
    text = text.replace("_", "\\_")
    text = text.replace("*", "\\*")
    text = text.replace("[", "\\[")
    text = text.replace("`", "\\`")
    text = text.replace("(", "\\(")
    text = text.replace(")", "\\)")
    text = text.replace("~", "\\~")
    text = text.replace(">", "\\>")
    text = text.replace("#", "\\#")
    text = text.replace("+", "\\+")
    text = text.replace("-", "\\-")
    text = text.replace("=", "\\=")
    text = text.replace("|", "\\|")
    text = text.replace("{", "\\{")
    text = text.replace("}", "\\}")
    text = text.replace(".", "\\.")
    text = text.replace("!", "\\!")
    return text
