/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  QuestionOut
} from '.././model'



  /**
 * @summary Get Random Question
 */
export const getRandomQuestion = <TData = AxiosResponse<QuestionOut>>(
    candidateUuid: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8000/api/question/${candidateUuid}`,options
    );
  }
export type GetRandomQuestionResult = AxiosResponse<QuestionOut>
