/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  QuestionOut
} from '.././model'

export const getGetRandomQuestionResponseMock = (overrideResponse: Partial< QuestionOut > = {}): QuestionOut => ({question: faker.helpers.arrayElement([{current_progress: faker.number.int({min: undefined, max: undefined}), text: faker.word.sample(), variants: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: undefined, max: undefined}), text: faker.word.sample()}))},null]), ...overrideResponse})


export const getGetRandomQuestionMockHandler = (overrideResponse?: QuestionOut | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => QuestionOut)) => {
  return http.get('*/api/question/:candidateUuid', async (info) => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? overrideResponse(info) : overrideResponse) 
            : getGetRandomQuestionResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getQuestionMock = () => [
  getGetRandomQuestionMockHandler()]
