/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import {
  ResponseStatus
} from '.././model'
import type {
  ResponseModal
} from '.././model'

export const getContactFormResponseMock = (overrideResponse: Partial< ResponseModal > = {}): ResponseModal => ({status: faker.helpers.arrayElement(Object.values(ResponseStatus)), ...overrideResponse})


export const getContactFormMockHandler = (overrideResponse?: ResponseModal | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => ResponseModal)) => {
  return http.post('*/api/client/contact_form', async (info) => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? overrideResponse(info) : overrideResponse) 
            : getContactFormResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getClientMock = () => [
  getContactFormMockHandler()]
