/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  BodyContactForm,
  ResponseModal
} from '.././model'



  /**
 * @summary Contact Form
 */
export const contactForm = <TData = AxiosResponse<ResponseModal>>(
    bodyContactForm: BodyContactForm, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
formData.append('name', bodyContactForm.name)
formData.append('email', bodyContactForm.email)
formData.append('phone', bodyContactForm.phone)
formData.append('message', bodyContactForm.message)
if(bodyContactForm.file !== undefined) {
 formData.append('file', bodyContactForm.file)
 }
if(bodyContactForm.bot_ip !== undefined) {
 formData.append('bot_ip', bodyContactForm.bot_ip)
 }
if(bodyContactForm.candidate_uuid !== undefined) {
 formData.append('candidate_uuid', bodyContactForm.candidate_uuid)
 }
if(bodyContactForm.language !== undefined) {
 formData.append('language', bodyContactForm.language)
 }

    return axios.post(
      `http://back/api/client/contact_form`,
      formData,options
    );
  }
export type ContactFormResult = AxiosResponse<ResponseModal>
