/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'



  /**
 * @summary Check Blacklist Ip
 */
export const checkBlacklistIp = <TData = AxiosResponse<unknown>>(
    ip: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://back/api/blcaklist_ips/${ip}/check`,options
    );
  }
export type CheckBlacklistIpResult = AxiosResponse<unknown>
