/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import {
  HttpResponse,
  delay,
  http
} from 'msw'


export const getCheckBlacklistIpMockHandler = () => {
  return http.get('*/api/blcaklist_ips/:ip/check', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getBlacklistIPMock = () => [
  getCheckBlacklistIpMockHandler()]
