/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  CaseOut,
  CasesOut
} from '.././model'

export const getGetAllCasesResponseMock = (overrideResponse: Partial< CasesOut > = {}): CasesOut => ({cases: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({description: faker.word.sample(), mainImageUrl: faker.word.sample(), previewImageUrl: faker.word.sample(), projectLink: faker.helpers.arrayElement([faker.word.sample(),null]), role: faker.word.sample(), screenshotsUrls: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), slugName: faker.word.sample(), stacksNames: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), subTitle: faker.word.sample(), title: faker.word.sample()})), ...overrideResponse})

export const getGetCaseBySlugResponseMock = (overrideResponse: Partial< CaseOut > = {}): CaseOut => ({description: faker.word.sample(), mainImageUrl: faker.word.sample(), previewImageUrl: faker.word.sample(), projectLink: faker.helpers.arrayElement([faker.word.sample(),null]), role: faker.word.sample(), screenshotsUrls: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), slugName: faker.word.sample(), stacksNames: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), subTitle: faker.word.sample(), title: faker.word.sample(), ...overrideResponse})


export const getGetAllCasesMockHandler = (overrideResponse?: CasesOut | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => CasesOut)) => {
  return http.get('*/api/cases/', async (info) => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? overrideResponse(info) : overrideResponse) 
            : getGetAllCasesResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetCaseBySlugMockHandler = (overrideResponse?: CaseOut | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => CaseOut)) => {
  return http.get('*/api/cases/:slugName', async (info) => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? overrideResponse(info) : overrideResponse) 
            : getGetCaseBySlugResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getCaseMock = () => [
  getGetAllCasesMockHandler(),
  getGetCaseBySlugMockHandler()]
