/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CaseOut,
  CasesOut,
  GetAllCasesParams,
  GetCaseBySlugParams
} from '.././model'



  /**
 * @summary Get
 */
export const getAllCases = <TData = AxiosResponse<CasesOut>>(
    params?: GetAllCasesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://back/api/cases/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Get By Slug
 */
export const getCaseBySlug = <TData = AxiosResponse<CaseOut>>(
    slugName: string,
    params?: GetCaseBySlugParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://back/api/cases/${slugName}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export type GetAllCasesResult = AxiosResponse<CasesOut>
export type GetCaseBySlugResult = AxiosResponse<CaseOut>
