/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.17
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  Device,
  DeviceToken
} from '.././model'



  /**
 * @summary Create Device
 */
export const createDeviceApiDevicePost = <TData = AxiosResponse<Device>>(
    deviceToken: DeviceToken, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:5000/api/device`,
      deviceToken,options
    );
  }
export type CreateDeviceApiDevicePostResult = AxiosResponse<Device>
