/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  Device
} from '.././model'

export const getCreateDeviceApiDevicePostResponseMock = (overrideResponse: Partial< Device > = {}): Device => ({is_deleted: faker.datatype.boolean(), token: faker.word.sample(), uid: faker.word.sample(), ...overrideResponse})


export const getCreateDeviceApiDevicePostMockHandler = (overrideResponse?: Device | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Device)) => {
  return http.post('*/api/device', async (info) => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? overrideResponse(info) : overrideResponse) 
            : getCreateDeviceApiDevicePostResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getDeviceMock = () => [
  getCreateDeviceApiDevicePostMockHandler()]
