/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'



  /**
 * @summary Root
 */
export const rootGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://back/`,options
    );
  }
