/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.17
 */

export interface BodyApplicationForm {
  candidate_uuid?: string;
  email: string;
  file?: Blob;
  message: string;
  name: string;
  phone: string;
}
