/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.17
 */
import type { Languages } from './languages';

export interface BodyContactForm {
  bot_ip?: string;
  candidate_uuid?: string;
  email: string;
  file?: Blob;
  language?: Languages;
  message?: string;
  name: string;
  phone: string;
}
