/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.17
 */
import type { CaseOutProjectLink } from './caseOutProjectLink';

export interface CaseOut {
  description: string;
  mainImageUrl: string;
  previewImageUrl: string;
  projectLink: CaseOutProjectLink;
  role: string;
  screenshotsUrls: string[];
  slugName: string;
  stacksNames: string[];
  subTitle: string;
  title: string;
}
