/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.17
 */
import type { FeedBackLink } from './feedBackLink';
import type { FeedBackProjectName } from './feedBackProjectName';

export interface FeedBack {
  clientName: string;
  comment: string;
  link: FeedBackLink;
  projectName: FeedBackProjectName;
  uuid: string;
}
