/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.17
 */
import type { Languages } from './languages';

export type GetCaseBySlugParams = {
lang?: Languages;
};
