/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import type { IsAuthenticatedImageUrl } from './isAuthenticatedImageUrl';

export interface IsAuthenticated {
  email: string;
  git_hub_id: string;
  image_url?: IsAuthenticatedImageUrl;
  username: string;
}
