/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */

export type Languages = typeof Languages[keyof typeof Languages];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Languages = {
  en: 'en',
  de: 'de',
} as const;
