/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import type { Question } from './question';

export type QuestionOutQuestion = Question | null;
