/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import type { VariantQuestion } from './variantQuestion';

export interface Question {
  current_progress: number;
  text: string;
  variants: VariantQuestion[];
}
