/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */

export type ResponseStatus = typeof ResponseStatus[keyof typeof ResponseStatus];


export const ResponseStatus = {
  fail: 'fail',
  success: 'success',
} as const;
