/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.17
 */

export type ResponseStatus = typeof ResponseStatus[keyof typeof ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseStatus = {
  fail: 'fail',
  success: 'success',
} as const;
