"""uuid

Revision ID: 3035aa2ce5e1
Revises: 7cc0cd3bee9d
Create Date: 2023-04-20 15:55:53.659311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3035aa2ce5e1'
down_revision = '7cc0cd3bee9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###