"""github openid key

Revision ID: 7cc0cd3bee9d
Revises: 6b16dbf63673
Create Date: 2023-04-20 15:54:20.121704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc0cd3bee9d'
down_revision = '6b16dbf63673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_openid_key', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_openid_key')
    # ### end Alembic commands ###