"""add feedbacks

Revision ID: 026af435337e
Revises: 2c4fe963df46
Create Date: 2024-06-24 10:09:00.943329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026af435337e'
down_revision = '2c4fe963df46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('client_name', sa.String(length=128), nullable=False),
    sa.Column('project_name', sa.String(length=128), nullable=False),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedbacks'))
    )
    op.create_index(op.f('ix_feedbacks_uuid'), 'feedbacks', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_uuid'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
