"""add enum case image

Revision ID: 0e4692c80ffb
Revises: 3a1be7ab8d57
Create Date: 2023-08-02 16:37:22.555931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0e4692c80ffb"
down_revision = "3a1be7ab8d57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=32), nullable=False),
        sa.Column("sub_title", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("project_link", sa.String(length=128), nullable=True),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
        sa.UniqueConstraint("title", name=op.f("uq_cases_title")),
    )
    op.create_table(
        "stacks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stacks")),
    )
    op.create_table(
        "case_images",
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column(
            "type_of_image",
            sa.Enum("case_main_image", "case_preview_image", name="enumcaseimagetype"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=256), nullable=False),
        sa.Column("origin_file_name", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_case_images_case_id_cases")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_images")),
    )
    op.create_table(
        "case_screenshots",
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=256), nullable=False),
        sa.Column("origin_file_name", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_case_screenshots_case_id_cases")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_screenshots")),
    )
    op.create_table(
        "case_stacks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("stack_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_case_stacks_case_id_cases")
        ),
        sa.ForeignKeyConstraint(
            ["stack_id"], ["stacks.id"], name=op.f("fk_case_stacks_stack_id_stacks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_stacks")),
    )
    op.alter_column(
        "candidate_answers", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "candidate_answers", "answer_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "candidate_answers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.add_column("candidates", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.alter_column(
        "candidates", "quiz_score", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "candidates", "uuid", existing_type=sa.VARCHAR(length=36), nullable=False
    )
    op.alter_column(
        "candidates", "email", existing_type=sa.VARCHAR(length=128), nullable=True
    )
    op.alter_column(
        "candidates", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "candidates", "is_verified", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_constraint("uq_candidates_username", "candidates", type_="unique")
    op.create_index(op.f("ix_candidates_uuid"), "candidates", ["uuid"], unique=False)
    op.alter_column(
        "candidates_resumes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "candidates_resumes", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.add_column("questions", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.add_column(
        "superusers", sa.Column("unique_id", sa.String(length=36), nullable=False)
    )
    op.add_column(
        "superusers",
        sa.Column("reset_password_uid", sa.String(length=64), nullable=False),
    )
    op.add_column("superusers", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.alter_column(
        "superusers", "uuid", existing_type=sa.VARCHAR(length=36), nullable=False
    )
    op.alter_column(
        "superusers", "email", existing_type=sa.VARCHAR(length=128), nullable=True
    )
    op.alter_column(
        "superusers", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "superusers", "is_verified", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_constraint("uq_superusers_username", "superusers", type_="unique")
    op.create_index(op.f("ix_superusers_uuid"), "superusers", ["uuid"], unique=False)
    op.alter_column(
        "variant_answers", "question_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "variant_answers", "question_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_index(op.f("ix_superusers_uuid"), table_name="superusers")
    op.create_unique_constraint("uq_superusers_username", "superusers", ["username"])
    op.alter_column(
        "superusers", "is_verified", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "superusers", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "superusers", "email", existing_type=sa.VARCHAR(length=128), nullable=False
    )
    op.alter_column(
        "superusers", "uuid", existing_type=sa.VARCHAR(length=36), nullable=True
    )
    op.drop_column("superusers", "is_deleted")
    op.drop_column("superusers", "reset_password_uid")
    op.drop_column("superusers", "unique_id")
    op.drop_column("questions", "is_deleted")
    op.alter_column(
        "candidates_resumes", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "candidates_resumes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_index(op.f("ix_candidates_uuid"), table_name="candidates")
    op.create_unique_constraint("uq_candidates_username", "candidates", ["username"])
    op.alter_column(
        "candidates", "is_verified", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "candidates", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "candidates", "email", existing_type=sa.VARCHAR(length=128), nullable=False
    )
    op.alter_column(
        "candidates", "uuid", existing_type=sa.VARCHAR(length=36), nullable=True
    )
    op.alter_column(
        "candidates", "quiz_score", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("candidates", "is_deleted")
    op.alter_column(
        "candidate_answers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "candidate_answers", "answer_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "candidate_answers", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_table("case_stacks")
    op.drop_table("case_screenshots")
    op.drop_table("case_images")
    op.drop_table("stacks")
    op.drop_table("cases")
    # ### end Alembic commands ###
