"""added new field for cases sub_title_img

Revision ID: 10d909730297
Revises: f8b06a7916bf
Create Date: 2023-07-27 10:58:08.890050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d909730297'
down_revision = 'f8b06a7916bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('sub_title_image_url', sa.String(length=256), nullable=False))
    op.alter_column('cases', 'title_image_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'title_image_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_column('cases', 'sub_title_image_url')
    # ### end Alembic commands ###
