"""quiz_score field

Revision ID: 3a1be7ab8d57
Revises: e5bd15a56627
Create Date: 2023-06-23 15:36:04.642168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1be7ab8d57'
down_revision = 'e5bd15a56627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('quiz_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'quiz_score')
    # ### end Alembic commands ###
