"""add language to case

Revision ID: 63a3fda1a9cd
Revises: b581353d04f2
Create Date: 2023-09-07 11:24:30.548742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a3fda1a9cd'
down_revision = 'b581353d04f2'
branch_labels = None
depends_on = None

languages_enum = sa.Enum('ENGLISH', 'GERMANY', name='languages')
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    languages_enum.create(op.get_bind())
    op.add_column('cases', sa.Column('language', languages_enum, nullable=True))
    op.execute(
        f"UPDATE cases SET language = 'ENGLISH' WHERE language is null"
    )
    op.alter_column("cases", "language", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'language')
    # ### end Alembic commands ###
    languages_enum.drop(op.get_bind())
