"""added cases is_main field

Revision ID: 79d94bb68068
Revises: a5762cc72a47
Create Date: 2023-08-01 10:20:29.886628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d94bb68068'
down_revision = 'a5762cc72a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('is_main', sa.Boolean(), nullable=True))
    op.execute("UPDATE cases SET is_main = false")
    op.alter_column("cases", "is_main", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'is_main')
    # ### end Alembic commands ###
