"""add is_deleted to question

Revision ID: 9a83809eca01
Revises: 10d909730297
Create Date: 2023-07-27 12:40:42.288889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9a83809eca01"
down_revision = "10d909730297"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.execute("UPDATE questions SET is_deleted = false")
    op.alter_column("questions", "is_deleted", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "is_deleted")
    # ### end Alembic commands ###
