"""added unique case title

Revision ID: a5762cc72a47
Revises: 9a83809eca01
Create Date: 2023-07-28 16:47:20.018842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5762cc72a47'
down_revision = '9a83809eca01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_cases_title'), 'cases', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_cases_title'), 'cases', type_='unique')
    # ### end Alembic commands ###
