"""check connect to common orm

Revision ID: bc5c785121be
Revises: 3a1be7ab8d57
Create Date: 2023-07-24 16:12:47.826640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc5c785121be'
down_revision = '3a1be7ab8d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_answers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('candidate_answers', 'answer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('candidate_answers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('candidates', 'quiz_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('candidates', 'uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('candidates', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('candidates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('candidates', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_candidates_uuid'), 'candidates', ['uuid'], unique=False)
    op.alter_column('candidates_resumes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('candidates_resumes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('superusers', sa.Column('unique_id', sa.String(length=36), nullable=False))
    op.add_column('superusers', sa.Column('reset_password_uid', sa.String(length=64), nullable=False))
    op.alter_column('superusers', 'uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('superusers', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('superusers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('superusers', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_superusers_uuid'), 'superusers', ['uuid'], unique=False)
    op.alter_column('variant_answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variant_answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_superusers_uuid'), table_name='superusers')
    op.alter_column('superusers', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('superusers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('superusers', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('superusers', 'uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('superusers', 'reset_password_uid')
    op.drop_column('superusers', 'unique_id')
    op.alter_column('candidates_resumes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('candidates_resumes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_candidates_uuid'), table_name='candidates')
    op.alter_column('candidates', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('candidates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('candidates', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('candidates', 'uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('candidates', 'quiz_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('candidate_answers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('candidate_answers', 'answer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('candidate_answers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
