"""add order index

Revision ID: e52e74703ee7
Revises: 026af435337e
Create Date: 2024-07-02 10:34:12.660046

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e52e74703ee7"
down_revision = "026af435337e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cases",
        sa.Column("order_index", sa.Integer(), nullable=False, server_default="1"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cases", "order_index")
    # ### end Alembic commands ###
