"""added current_question_id

Revision ID: e5bd15a56627
Revises: 067daf773acc
Create Date: 2023-06-21 17:22:31.300146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bd15a56627'
down_revision = '067daf773acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('current_question_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'current_question_id')
    # ### end Alembic commands ###
