"""add cases and stacks and case_image and case_stack

Revision ID: f8b06a7916bf
Revises: bc5c785121be
Create Date: 2023-07-25 16:57:52.223553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b06a7916bf'
down_revision = 'bc5c785121be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('title_image_url', sa.String(length=256), nullable=True),
    sa.Column('sub_title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('project_link', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    op.create_table('stacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stacks'))
    )
    op.create_table('case_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_images_case_id_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_images'))
    )
    op.create_table('case_stacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('stack_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_stacks_case_id_cases')),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], name=op.f('fk_case_stacks_stack_id_stacks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_stacks'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_stacks')
    op.drop_table('case_images')
    op.drop_table('stacks')
    op.drop_table('cases')
    # ### end Alembic commands ###
