/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.17
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  FeedBack
} from '.././model'



  /**
 * @summary Get Feedbacks
 */
export const getFeedbacksApiFeedbacksGet = <TData = AxiosResponse<FeedBack[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:5000/api/feedbacks/`,options
    );
  }
export type GetFeedbacksApiFeedbacksGetResult = AxiosResponse<FeedBack[]>
