/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  BodyApplicationForm,
  CandidateAnswer,
  CandidateAnswerOut,
  IsAuthenticated,
  IsAuthenticatedOut,
  ResponseModal
} from '.././model'



  /**
 * @summary Is Authenticated
 */
export const isAuthenticated = <TData = AxiosResponse<IsAuthenticatedOut>>(
    isAuthenticated: IsAuthenticated, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:8000/api/candidate/is_authenticated`,
      isAuthenticated,options
    );
  }
/**
 * @summary Set Answer
 */
export const setAnswer = <TData = AxiosResponse<CandidateAnswerOut>>(
    candidateAnswer: CandidateAnswer, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:8000/api/candidate/set_answer`,
      candidateAnswer,options
    );
  }
/**
 * @summary Application Form
 */
export const applicationForm = <TData = AxiosResponse<ResponseModal>>(
    bodyApplicationForm: BodyApplicationForm, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
formData.append('name', bodyApplicationForm.name)
formData.append('email', bodyApplicationForm.email)
formData.append('phone', bodyApplicationForm.phone)
formData.append('message', bodyApplicationForm.message)
if(bodyApplicationForm.file !== undefined) {
 formData.append('file', bodyApplicationForm.file)
 }
if(bodyApplicationForm.candidate_uuid !== undefined) {
 formData.append('candidate_uuid', bodyApplicationForm.candidate_uuid)
 }

    return axios.post(
      `http://localhost:8000/api/candidate/application_form`,
      formData,options
    );
  }
export type IsAuthenticatedResult = AxiosResponse<IsAuthenticatedOut>
export type SetAnswerResult = AxiosResponse<CandidateAnswerOut>
export type ApplicationFormResult = AxiosResponse<ResponseModal>
