/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import {
  ResponseStatus
} from '.././model'
import type {
  CandidateAnswerOut,
  IsAuthenticatedOut,
  ResponseModal
} from '.././model'

export const getIsAuthenticatedResponseMock = (overrideResponse: Partial< IsAuthenticatedOut > = {}): IsAuthenticatedOut => ({user_uuid: faker.word.sample(), ...overrideResponse})

export const getSetAnswerResponseMock = (overrideResponse: Partial< CandidateAnswerOut > = {}): CandidateAnswerOut => ({status: faker.word.sample(), ...overrideResponse})

export const getApplicationFormResponseMock = (overrideResponse: Partial< ResponseModal > = {}): ResponseModal => ({status: faker.helpers.arrayElement(Object.values(ResponseStatus)), ...overrideResponse})


export const getIsAuthenticatedMockHandler = (overrideResponse?: IsAuthenticatedOut | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => IsAuthenticatedOut)) => {
  return http.post('*/api/candidate/is_authenticated', async (info) => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? overrideResponse(info) : overrideResponse) 
            : getIsAuthenticatedResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getSetAnswerMockHandler = (overrideResponse?: CandidateAnswerOut | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => CandidateAnswerOut)) => {
  return http.post('*/api/candidate/set_answer', async (info) => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? overrideResponse(info) : overrideResponse) 
            : getSetAnswerResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getApplicationFormMockHandler = (overrideResponse?: ResponseModal | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => ResponseModal)) => {
  return http.post('*/api/candidate/application_form', async (info) => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? overrideResponse(info) : overrideResponse) 
            : getApplicationFormResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getCandidateMock = () => [
  getIsAuthenticatedMockHandler(),
  getSetAnswerMockHandler(),
  getApplicationFormMockHandler()]
