/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  StackOut
} from '.././model'



  /**
 * @summary Get
 */
export const getAllStacks = <TData = AxiosResponse<StackOut[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://back/api/stacks/`,options
    );
  }
export type GetAllStacksResult = AxiosResponse<StackOut[]>
