/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.5.9
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  StackOut
} from '.././model'

export const getGetAllStacksResponseMock = (): StackOut[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({name: faker.word.sample()})))


export const getGetAllStacksMockHandler = (overrideResponse?: StackOut[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => StackOut[])) => {
  return http.get('*/api/stacks/', async (info) => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? overrideResponse(info) : overrideResponse) 
            : getGetAllStacksResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getStacksMock = () => [
  getGetAllStacksMockHandler()]
