name: Build and Deploy

on:
  push:
    tags:
      - 'v*.*.*'

env:
  DOCKER_LOGIN: simple2b
  IMAGE_BACK: simple2b/site-s2b-back
  IMAGE_FRONT: simple2b/site-s2b-front
  DEPLOY_HOST: ${{ secrets.DEVELOP_HOST }}
  DEPLOY_USER_NAME: ${{ secrets.DEVELOP_USERNAME }}
  DEPLOY_SSH_KEY: ${{ secrets.DEVELOP_SSH_KEY }}
  DEPLOY_SSH_PORT: 2222
  SITE_DOCKER_ACCESS_TOKEN: ${{ secrets.SITE_DOCKER_ACCESS_TOKEN }}

jobs:
  on-develop-branch-check:
    runs-on: Linux
    outputs:
      on_develop: ${{ steps.contains_tag.outputs.retval }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: rickstaa/action-contains-tag@v1
        id: contains_tag
        with:
          reference: 'develop'
          tag: '${{ github.ref }}'
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']
        poetry-version: [1.5.1]
        os: [Linux]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        working-directory: ./back
        run: |
          poetry install
      - name: Lint with flake8
        working-directory: ./back
        run: |
          poetry run flake8 . --count --show-source --statistics
          poetry run flake8 . --count --exit-zero --max-complexity=10 --statistics
      - name: Run pytest
        working-directory: ./back
        run: |
          poetry run pytest
  build:
    runs-on: Linux
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker meta
        id: meta_front
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.IMAGE_FRONT }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Docker meta
        id: meta_back
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.IMAGE_BACK }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_LOGIN }}
          password: ${{ env.SITE_DOCKER_ACCESS_TOKEN }}
      - name: Build and Push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./back
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_back.outputs.tags }}
          labels: ${{ steps.meta_back.outputs.labels }}
      - name: Build and Push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./front
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_front.outputs.tags }}
          labels: ${{ steps.meta_front.outputs.labels }}
  deploy:
    name: Deploy to staging
    runs-on: Linux
    needs:
      # - on-develop-branch-check
      - build
    # if: ${{ needs.on-develop-branch-check.outputs.on_develop == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - name: update compose file
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER_NAME }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          port: ${{ env.DEPLOY_SSH_PORT }}
          source: docker-compose.dev.yaml
          target: ~/site_dev
      - name: deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER_NAME }}
          port: ${{ env.DEPLOY_SSH_PORT }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          script: |
            cd ~/site_dev &&
            mv docker-compose.dev.yaml docker-compose.yaml &&
            docker compose pull &&
            docker compose up -d &&
            docker system prune -f
