# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy on staging

on:
  push:
    branches:
      - develop
    tags:
      - "v*.*.*"

env:
  DOCKER_LOGIN: simple2b
  DEPLOY_HOST: ${{ secrets.DEVELOP_HOST }}
  DEPLOY_USER_NAME: ${{ secrets.DEVELOP_USERNAME }}
  DEPLOY_SSH_KEY: ${{ secrets.DEVELOP_SSH_KEY }}

jobs:
  deploy:
    runs-on: Linux
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: update compose file
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER_NAME }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          source: docker-compose.dev.yaml
          target: ~/site_dev
      - name: deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER_NAME }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          script: |
            cd ~/site_dev &&
            mv docker-compose.dev.yaml docker-compose.yaml &&
            docker-compose pull &&
            docker-compose up -d &&
            docker system prune -f
